name: practice
description: Practice techniques to improve skills

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  sqflite: ^1.1.7+1
  path_provider: ^0.4.1
  flutter_rating_bar: ^3.0.0
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/